name: test

on:
  push:
    branches:
      - main
      - develop

jobs:
  echo_env:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.echo_env.outputs.env_name }}
    steps:
      - uses: actions/checkout@v2
      - name: echo env
        id: echo_env
        run: |
          if [ "{{github.ref_name}}" = "main" ]; then
            echo "::set-output name=env_name::production"
          else
            echo "::set-output name=env_name::develop"
  echo_var:
    needs: ["echo_env"]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.echo_env.outputs.env_name }}
    steps:
      - run: echo ${{ vars.A }}